#include "main.h"

void _clk_init(void)
{
  RCU_APB2EN |= RCU_APB2EN_PAEN | RCU_APB2EN_PBEN | RCU_APB2EN_PCEN;
  RCU_APB2EN |= RCU_APB2EN_USART0EN;
  RCU_APB2EN |= RCU_APB2EN_TIMER0EN;
  RCU_APB2EN |= RCU_APB2EN_ADC0EN;

  RCU_AHBEN |= RCU_AHBEN_DMA0EN | RCU_AHBEN_DMA1EN;
  RCU_APB1EN |= RCU_APB1EN_TIMER1EN;
  RCU_APB1EN |= RCU_APB1EN_TIMER2EN;
  RCU_APB1EN |= RCU_APB1EN_TIMER3EN;

  rcu_adc_clock_config(RCU_CKADC_CKAPB2_DIV8);
}

void _gpio_init(void)
{
  gpio_init(GPIOC, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_13); // It's led for indicate activity
  gpio_init(GPIOA, GPIO_MODE_IPU, GPIO_OSPEED_50MHZ, GPIO_PIN_0);     // input signal
  gpio_init(GPIOA, GPIO_MODE_OUT_PP, GPIO_OSPEED_50MHZ, GPIO_PIN_10); // signal response
  gpio_init(GPIOB, GPIO_MODE_OUT_PP, GPIO_OSPEED_50MHZ, GPIO_PIN_0);  // inverted state for input caapture signal
  gpio_init(GPIOB, GPIO_MODE_AF_PP, GPIO_OSPEED_50MHZ, GPIO_PIN_1);   // PWM_12, TIM3_CH3
	gpio_init(GPIOA, GPIO_MODE_AF_PP, GPIO_OSPEED_50MHZ, GPIO_PIN_0);   // PWM_OUT, PA0
  gpio_init(GPIOA, GPIO_MODE_IPD, GPIO_OSPEED_50MHZ, GPIO_PIN_8); //REQUEST INPUT CAPTURE

  gpio_init(GPIOA, GPIO_MODE_AIN, GPIO_OSPEED_50MHZ, GPIO_PIN_2); // ADC0_CH2
  gpio_init(GPIOA, GPIO_MODE_AIN, GPIO_OSPEED_50MHZ, GPIO_PIN_3); // ADC0_CH3

  gpio_init(GPIOB, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_2);  // NSS_0
  gpio_init(GPIOB, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_10); // NSS_1
  gpio_init(GPIOA, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_7);  // SDI
  gpio_init(GPIOA, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_5);  // SCK

  gpio_init(GPIOB, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_7); // D8
  gpio_init(GPIOB, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_6); // D9
}

void _usart_init(void)
{
  usart_deinit(USART0);
  usart_baudrate_set(USART0, 115200UL);
  usart_parity_config(USART0, USART_PM_NONE);
  usart_transmit_config(USART0, USART_TRANSMIT_ENABLE);
  gpio_afio_deinit();
  gpio_init(GPIOA, GPIO_MODE_AF_PP, GPIO_OSPEED_50MHZ, GPIO_PIN_9);
  usart_enable(USART0);
}

// This timer used for input capture signal from request line
void _tim0_init(void)
{
  // CONFIGURE INPUT FILTER
  TIMER_PSC(TIMER0) = 10799U; //Fsampling is 10 kHz
  TIMER_CAR(TIMER0) = 0xFFFF; //Get MAX. value
	TIMER_CHCTL0(TIMER0) |= (1<<9 | 1<<0); //CH0 - RISING EDGE, CH1 - FALLING EDGE
	TIMER_CHCTL2(TIMER0) |= TIMER_CHCTL2_CH0EN | TIMER_CHCTL2_CH1EN | TIMER_CHCTL2_CH1P;
	TIMER_DMAINTEN(TIMER0) |= TIMER_DMAINTEN_CH0IE | TIMER_DMAINTEN_CH1IE;
  TIMER_CTL0(TIMER0) |= TIMER_CTL0_CEN;
}

// Used for generation pwm_11
void _tim1_init(void)
{
	TIMER_PSC(TIMER1) = 1079;
	TIMER_CAR(TIMER1) = 1000;
	TIMER_CTL0(TIMER1) |= TIMER_CTL0_ARSE;//SHADOW ENABLE
	TIMER_CHCTL0(TIMER1) |= (1<<6|1<<5);//ENABLE PWM MODE 0
	TIMER_CH0CV(TIMER1) = 100; //DEFAULT 10% PWM FILLING
	TIMER_CHCTL2(TIMER1) |= TIMER_CHCTL2_CH0EN;
	TIMER_CTL0(TIMER1) |= TIMER_CTL0_CEN;
}
//PWM12 GENERATION
void _tim2_init(void)
{

	TIMER_PSC(TIMER2) = 1079;
	TIMER_CAR(TIMER2) = 1000;
	TIMER_CTL0(TIMER2) |= TIMER_CTL0_ARSE;//SHADOW ENABLE
	TIMER_CHCTL1(TIMER2) |= (1<<14|1<<13);//ENABLE PWM MODE 0
	TIMER_CH3CV(TIMER2) = 100; //DEFAULT 10% PWM FILLING
	TIMER_CH2CV(TIMER2) = 100; //DEFAULT 10% PWM FILLING
	TIMER_CHCTL2(TIMER2) |= TIMER_CHCTL2_CH3EN;
	TIMER_CTL0(TIMER2) |= TIMER_CTL0_CEN;
}


void _adc_init(void)
{
  adc_deinit(ADC0);
  adc_mode_config(ADC_MODE_FREE);
  adc_data_alignment_config(ADC0, ADC_DATAALIGN_RIGHT); // LSB alignment
  ADC_CTL1(ADC0) |= (1 << 19 | 1 << 18 | 1 << 17);
  adc_regular_channel_config(ADC0, 0, ADC_CHANNEL_3, ADC_SAMPLETIME_1POINT5); // WHAT IS RANK??? (0 value)
  adc_enable(ADC0);
}
